phase_name: "Cost Guardrails - Budget Control & Anomaly Detection with FinOps Enforcement"
description: "AWS Budgets, Cost Anomaly Detection and automated FinOps enforcement for proactive cost management"
resource_count: 6

Resources:
  # Project Budget with Alerts
  ProjectBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub '${ProjectName}-monthly-budget'
        BudgetLimit:
          Amount: !Ref MonthlyBudgetLimit
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
        CostFilters:
          TagKey:
            - Project
          TagValue:
            - !Ref ProjectName
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlertEmail
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlertEmail

  # Control Plane Budget (separate from workloads)
  ControlPlaneBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub '${ProjectName}-control-plane-budget'
        BudgetLimit:
          Amount: !Ref ControlPlaneBudgetLimit
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
        CostFilters:
          TagKey:
            - "ial:deployment-type"
          TagValue:
            - "control_plane"
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 90
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlertEmail

  # Cost Anomaly Detector
  CostAnomalyDetector:
    Type: AWS::CE::AnomalyDetector
    Properties:
      AnomalyDetectorName: !Sub '${ProjectName}-cost-anomaly-detector'
      MonitorType: DIMENSIONAL
      MonitorSpecification: |
        {
          "DimensionKey": "SERVICE",
          "MatchOptions": ["EQUALS"],
          "Values": ["Amazon Elastic Compute Cloud - Compute", "Amazon Relational Database Service", "Amazon Simple Storage Service"]
        }

  # Cost Anomaly Monitor
  CostAnomalyMonitor:
    Type: AWS::CE::AnomalyMonitor
    Properties:
      MonitorName: !Sub '${ProjectName}-cost-monitor'
      MonitorType: DIMENSIONAL
      MonitorSpecification: !Sub |
        {
          "Tags": {
            "Key": "Project",
            "Values": ["${ProjectName}"],
            "MatchOptions": ["EQUALS"]
          }
        }

  # Cost Anomaly Subscription
  CostAnomalySubscription:
    Type: AWS::CE::AnomalySubscription
    Properties:
      SubscriptionName: !Sub '${ProjectName}-cost-alerts'
      MonitorArnList:
        - !Ref CostAnomalyMonitor
      Subscribers:
        - Type: EMAIL
          Address: !Ref AlertEmail
      Frequency: DAILY
      Threshold: 10.0

  # FinOps Enforcement SNS Topic
  FinOpsAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-finops-alerts'
      DisplayName: 'IAL FinOps Budget Enforcement Alerts'
      Subscription:
        - Protocol: email
          Endpoint: !Ref AlertEmail

# Outputs
Outputs:
  BudgetName:
    Description: 'Name of the project budget'
    Value: !Sub '${ProjectName}-monthly-budget'
    Export:
      Name: !Sub '${ProjectName}-budget-name'

  ControlPlaneBudgetName:
    Description: 'Name of the control plane budget'
    Value: !Sub '${ProjectName}-control-plane-budget'
    Export:
      Name: !Sub '${ProjectName}-control-plane-budget-name'

  AnomalyDetectorArn:
    Description: 'ARN of the cost anomaly detector'
    Value: !Ref CostAnomalyDetector
    Export:
      Name: !Sub '${ProjectName}-anomaly-detector-arn'

  CostMonitorArn:
    Description: 'ARN of the cost monitor'
    Value: !Ref CostAnomalyMonitor
    Export:
      Name: !Sub '${ProjectName}-cost-monitor-arn'

  FinOpsAlertsTopicArn:
    Description: 'ARN of the FinOps alerts SNS topic'
    Value: !Ref FinOpsAlertsTopic
    Export:
      Name: !Sub '${ProjectName}-finops-alerts-topic-arn'

# Cost estimation with FinOps integration
metadata:
  estimated_monthly_cost: '$3.50'
  cost_breakdown:
    budgets_api: '$0.60'
    cost_anomaly_detection: '$1.00'
    cost_explorer_api: '$0.40'
    sns_notifications: '$0.50'
    finops_enforcement: '$1.00'
  finops:
    enforcement_enabled: true
    budget_validation: true
    pr_commenting: true

# Parameters
parameters:
  ProjectName:
    Type: String
    Default: ial
  AlertEmail:
    Type: String
    Default: admin@example.com
    Description: Email address for cost alerts
  MonthlyBudgetLimit:
    Type: Number
    Default: 500
    Description: Monthly budget limit in USD for workloads
  ControlPlaneBudgetLimit:
    Type: Number
    Default: 200
    Description: Monthly budget limit in USD for control plane
