AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAL Foundation - DynamoDB State Tables'

Parameters:
  ProjectName:
    Type: String
    Default: ial-fork
    Description: Project name for resource naming

Resources:
  # Main state table
  StateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-state'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: StateTracking

  # MCP provisioning checklist table
  MCPProvisioningTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mcp-provisioning-checklist
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: resource_id
          AttributeType: S
      KeySchema:
        - AttributeName: resource_id
          KeyType: HASH
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: MCPProvisioning

Outputs:
  StateTableName:
    Description: Name of the state table
    Value: !Ref StateTable
    Export:
      Name: !Sub '${ProjectName}-StateTableName'
  
  StateTableArn:
    Description: ARN of the state table
    Value: !GetAtt StateTable.Arn
    Export:
      Name: !Sub '${ProjectName}-StateTableArn'
