AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAL Foundation - Reconciliation Engine Lambda'

Parameters:
  ProjectName:
    Type: String
    Default: ial-fork
    Description: Project name for resource naming

Resources:
  # IAM Role for Reconciliation Lambda
  ReconciliationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-reconciliation-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ReconciliationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !Sub 'arn:aws:dynamodb:*:*:table/${ProjectName}-*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  # Reconciliation Lambda Function
  ReconciliationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-reconciliation-engine'
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !GetAtt ReconciliationRole.Arn
      Timeout: 300
      MemorySize: 256
      Code:
        ZipFile: |
          import json
          import boto3
          import logging
          
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          def lambda_handler(event, context):
              """
              IAL Reconciliation Engine - Drift Detection and State Reconciliation
              """
              logger.info(f"Reconciliation event: {event}")
              
              try:
                  # Extract resource information
                  resource_type = event.get('resource_type', 'unknown')
                  resource_id = event.get('resource_id', 'unknown')
                  desired_state = event.get('desired_state', {})
                  
                  # Perform reconciliation logic
                  result = perform_reconciliation(resource_type, resource_id, desired_state)
                  
                  return {
                      'statusCode': 200,
                      'body': json.dumps({
                          'message': 'Reconciliation completed',
                          'resource_type': resource_type,
                          'resource_id': resource_id,
                          'drift_detected': result.get('drift_detected', False),
                          'actions_taken': result.get('actions_taken', []),
                          'timestamp': context.aws_request_id
                      })
                  }
                  
              except Exception as e:
                  logger.error(f"Reconciliation error: {str(e)}")
                  return {
                      'statusCode': 500,
                      'body': json.dumps({
                          'error': str(e),
                          'resource_type': resource_type,
                          'resource_id': resource_id
                      })
                  }
          
          def perform_reconciliation(resource_type, resource_id, desired_state):
              """Perform actual reconciliation logic"""
              # This would contain the actual reconciliation logic
              # For now, return a basic response
              return {
                  'drift_detected': False,
                  'actions_taken': ['state_verified'],
                  'reconciliation_status': 'completed'
              }
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: Reconciliation

Outputs:
  ReconciliationFunctionArn:
    Description: ARN of the reconciliation function
    Value: !GetAtt ReconciliationFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-ReconciliationFunctionArn'
  
  ReconciliationFunctionName:
    Description: Name of the reconciliation function
    Value: !Ref ReconciliationFunction
    Export:
      Name: !Sub '${ProjectName}-ReconciliationFunctionName'
