AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAL Foundation - Backup Strategy'

Parameters:
  ProjectName:
    Type: String
    Default: ial-fork
    Description: Project name for resource naming

Resources:
  # S3 Bucket for configuration backups
  ConfigurationBackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-config-backups-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: ConfigBackups

  # IAM Role for backup operations
  BackupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-backup-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BackupPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource: 
                  - !Sub '${ConfigurationBackupBucket}/*'
                  - !GetAtt ConfigurationBackupBucket.Arn
              - Effect: Allow
                Action:
                  - dynamodb:CreateBackup
                  - dynamodb:DescribeBackup
                  - dynamodb:ListBackups
                  - dynamodb:RestoreTableFromBackup
                Resource: !Sub 'arn:aws:dynamodb:*:*:table/${ProjectName}-*'

  # Lambda function for automated backups
  BackupFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-backup-manager'
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !GetAtt BackupRole.Arn
      Timeout: 300
      MemorySize: 256
      Code:
        ZipFile: |
          import json
          import boto3
          import logging
          from datetime import datetime
          
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          def lambda_handler(event, context):
              """
              IAL Backup Manager - Automated backup operations
              """
              logger.info(f"Backup event: {event}")
              
              try:
                  backup_type = event.get('backup_type', 'configuration')
                  
                  if backup_type == 'configuration':
                      result = backup_configuration()
                  elif backup_type == 'dynamodb':
                      result = backup_dynamodb_tables()
                  else:
                      result = {'error': f'Unknown backup type: {backup_type}'}
                  
                  return {
                      'statusCode': 200,
                      'body': json.dumps({
                          'message': 'Backup completed',
                          'backup_type': backup_type,
                          'result': result,
                          'timestamp': datetime.utcnow().isoformat()
                      })
                  }
                  
              except Exception as e:
                  logger.error(f"Backup error: {str(e)}")
                  return {
                      'statusCode': 500,
                      'body': json.dumps({
                          'error': str(e),
                          'backup_type': backup_type
                      })
                  }
          
          def backup_configuration():
              """Backup configuration files to S3"""
              return {'status': 'completed', 'files_backed_up': 0}
          
          def backup_dynamodb_tables():
              """Create DynamoDB table backups"""
              return {'status': 'completed', 'tables_backed_up': 0}
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: BackupManager

  # EventBridge rule for scheduled backups
  BackupScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-backup-schedule'
      Description: 'Daily backup schedule for IAL infrastructure'
      ScheduleExpression: 'cron(0 2 * * ? *)'  # Daily at 2 AM UTC
      State: ENABLED
      Targets:
        - Arn: !GetAtt BackupFunction.Arn
          Id: BackupTarget
          Input: '{"backup_type": "configuration"}'

  # Permission for EventBridge to invoke Lambda
  BackupLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BackupFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BackupScheduleRule.Arn

Outputs:
  BackupBucketName:
    Description: Name of the backup bucket
    Value: !Ref ConfigurationBackupBucket
    Export:
      Name: !Sub '${ProjectName}-BackupBucketName'
  
  BackupFunctionArn:
    Description: ARN of the backup function
    Value: !GetAtt BackupFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-BackupFunctionArn'
