AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAL Foundation - Step Functions Orchestrator'

Parameters:
  ProjectName:
    Type: String
    Default: ial-fork
    Description: Project name for resource naming

Resources:
  # IAM Role for Step Functions
  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-stepfunctions-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSXRayDaemonWriteAccess
      Policies:
        - PolicyName: StepFunctionsExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub 'arn:aws:lambda:*:*:function:${ProjectName}-*'
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource: !Sub 'arn:aws:dynamodb:*:*:table/${ProjectName}-*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  # Main orchestrator state machine
  OrchestratorStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${ProjectName}-orchestrator'
      RoleArn: !GetAtt StepFunctionsRole.Arn
      StateMachineType: STANDARD
      DefinitionString: !Sub |
        {
          "Comment": "IAL Foundation Orchestrator",
          "StartAt": "InitializeOrchestration",
          "States": {
            "InitializeOrchestration": {
              "Type": "Pass",
              "Parameters": {
                "project_name": "${ProjectName}",
                "timestamp.$": "$$.State.EnteredTime",
                "execution_id.$": "$$.Execution.Name"
              },
              "Next": "ProcessRequest"
            },
            "ProcessRequest": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "${ProjectName}-processor",
                "Payload.$": "$"
              },
              "Next": "CheckResult"
            },
            "CheckResult": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.Payload.success",
                  "BooleanEquals": true,
                  "Next": "Success"
                }
              ],
              "Default": "Failure"
            },
            "Success": {
              "Type": "Succeed",
              "OutputPath": "$.Payload"
            },
            "Failure": {
              "Type": "Fail",
              "Cause": "Processing failed"
            }
          }
        }
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: Orchestration

  # Circuit breaker state machine
  CircuitBreakerStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${ProjectName}-circuit-breaker'
      RoleArn: !GetAtt StepFunctionsRole.Arn
      StateMachineType: EXPRESS
      DefinitionString: !Sub |
        {
          "Comment": "IAL Circuit Breaker Pattern",
          "StartAt": "CheckCircuitState",
          "States": {
            "CheckCircuitState": {
              "Type": "Task",
              "Resource": "arn:aws:states:::dynamodb:getItem",
              "Parameters": {
                "TableName": "${ProjectName}-state",
                "Key": {
                  "id": {
                    "S": "circuit-breaker-state"
                  }
                }
              },
              "Next": "EvaluateCircuit"
            },
            "EvaluateCircuit": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.Item.state.S",
                  "StringEquals": "OPEN",
                  "Next": "CircuitOpen"
                },
                {
                  "Variable": "$.Item.state.S",
                  "StringEquals": "HALF_OPEN",
                  "Next": "CircuitHalfOpen"
                }
              ],
              "Default": "CircuitClosed"
            },
            "CircuitClosed": {
              "Type": "Succeed",
              "Result": {
                "circuit_state": "CLOSED",
                "allow_request": true
              }
            },
            "CircuitHalfOpen": {
              "Type": "Succeed",
              "Result": {
                "circuit_state": "HALF_OPEN",
                "allow_request": true
              }
            },
            "CircuitOpen": {
              "Type": "Succeed",
              "Result": {
                "circuit_state": "OPEN",
                "allow_request": false
              }
            }
          }
        }
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: CircuitBreaker

Outputs:
  OrchestratorStateMachineArn:
    Description: ARN of the orchestrator state machine
    Value: !Ref OrchestratorStateMachine
    Export:
      Name: !Sub '${ProjectName}-OrchestratorStateMachineArn'
  
  CircuitBreakerStateMachineArn:
    Description: ARN of the circuit breaker state machine
    Value: !Ref CircuitBreakerStateMachine
    Export:
      Name: !Sub '${ProjectName}-CircuitBreakerStateMachineArn'
