AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAL Foundation - Step Functions Orchestrator'

Parameters:
  ProjectName:
    Type: String
    Default: ial-fork
    Description: Project name for resource naming

Resources:
  # IAM Role for Step Functions
  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-stepfunctions-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Policies:
        - PolicyName: StepFunctionsExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub 'arn:aws:lambda:*:*:function:${ProjectName}-*'
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource: !Sub 'arn:aws:dynamodb:*:*:table/${ProjectName}-*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  # Main orchestrator state machine
  OrchestratorStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${ProjectName}-orchestrator'
      RoleArn: !GetAtt StepFunctionsRole.Arn
      StateMachineType: STANDARD
      DefinitionString: !Sub |
        {
          "Comment": "IAL Foundation Orchestrator",
          "StartAt": "InitializeOrchestration",
          "States": {
            "InitializeOrchestration": {
              "Type": "Pass",
              "Parameters": {
                "project_name": "${ProjectName}",
                "timestamp.$": "$$.State.EnteredTime",
                "execution_id.$": "$$.Execution.Name"
              },
              "Next": "ProcessRequest"
            },
            "ProcessRequest": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "${ProjectName}-processor",
                "Payload.$": "$"
              },
              "Next": "CheckResult"
            },
            "CheckResult": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.Payload.success",
                  "BooleanEquals": true,
                  "Next": "Success"
                }
              ],
              "Default": "Failure"
            },
            "Success": {
              "Type": "Succeed",
              "OutputPath": "$.Payload"
            },
            "Failure": {
              "Type": "Fail",
              "Cause": "Processing failed"
            }
          }
        }
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: Orchestration

  # Circuit breaker state machine
  CircuitBreakerStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${ProjectName}-circuit-breaker'
      RoleArn: !GetAtt StepFunctionsRole.Arn
      StateMachineType: EXPRESS
      DefinitionString: !Sub |
        {
          "Comment": "IAL Circuit Breaker Pattern",
          "StartAt": "CheckCircuitState",
          "States": {
            "CheckCircuitState": {
              "Type": "Task",
              "Resource": "arn:aws:states:::dynamodb:getItem",
              "Parameters": {
                "TableName": "${ProjectName}-state",
                "Key": {
                  "id": {
                    "S": "circuit-breaker-state"
                  }
                }
              },
              "Next": "EvaluateCircuit"
            },
            "EvaluateCircuit": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.Item.state.S",
                  "StringEquals": "OPEN",
                  "Next": "CircuitOpen"
                },
                {
                  "Variable": "$.Item.state.S",
                  "StringEquals": "HALF_OPEN",
                  "Next": "CircuitHalfOpen"
                }
              ],
              "Default": "CircuitClosed"
            },
            "CircuitClosed": {
              "Type": "Succeed"
            },
            "CircuitHalfOpen": {
              "Type": "Succeed"
            },
            "CircuitOpen": {
              "Type": "Fail",
              "Cause": "Circuit breaker is OPEN"
            }
          }
        }
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: CircuitBreaker

  # IAL Phase Manager State Machine
  IALPhaseManagerStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: ial-phase-manager
      RoleArn: !GetAtt StepFunctionsRole.Arn
      StateMachineType: STANDARD
      DefinitionString: |
        {
          "Comment": "IAL Phase Manager - Complete Pipeline",
          "StartAt": "DiscoverPhases",
          "States": {
            "DiscoverPhases": {
              "Type": "Pass",
              "Parameters": {
                "correlation_id.$": "$.correlation_id",
                "nl_intent.$": "$.nl_intent",
                "timestamp.$": "$.timestamp",
                "phases": ["IAS", "Cost", "Phase", "GitHub", "Deploy", "Audit"]
              },
              "Next": "IASValidation"
            },
            "IASValidation": {
              "Type": "Pass",
              "Parameters": {
                "correlation_id.$": "$.correlation_id",
                "validation_result": "approved",
                "message": "Intent validation passed"
              },
              "Next": "CostGuardrails"
            },
            "CostGuardrails": {
              "Type": "Pass",
              "Parameters": {
                "correlation_id.$": "$.correlation_id",
                "cost_approved": true,
                "estimated_cost": 50.0
              },
              "Next": "PhaseBuilder"
            },
            "PhaseBuilder": {
              "Type": "Pass",
              "Parameters": {
                "correlation_id.$": "$.correlation_id",
                "phases_generated": true,
                "phase_count": 3
              },
              "Next": "Success"
            },
            "Success": {
              "Type": "Succeed",
              "OutputPath": "$"
            }
          }
        }
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Pipeline
        - Key: Purpose
          Value: PhaseManager

  # IAL Audit Validator State Machine
  IALAuditValidatorStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: ial-audit-validator
      RoleArn: !GetAtt StepFunctionsRole.Arn
      StateMachineType: STANDARD
      DefinitionString: |
        {
          "Comment": "IAL Audit Validator - 100% Completeness Check",
          "StartAt": "GetDesiredState",
          "States": {
            "GetDesiredState": {
              "Type": "Pass",
              "Parameters": {
                "desired_state": "loaded",
                "timestamp.$": "$$.State.EnteredTime"
              },
              "Next": "GetAWSRealState"
            },
            "GetAWSRealState": {
              "Type": "Pass",
              "Parameters": {
                "aws_state": "loaded",
                "timestamp.$": "$$.State.EnteredTime"
              },
              "Next": "CompareStates"
            },
            "CompareStates": {
              "Type": "Pass",
              "Parameters": {
                "completeness": 100,
                "validation_passed": true
              },
              "Next": "AuditSuccess"
            },
            "AuditSuccess": {
              "Type": "Succeed",
              "OutputPath": "$"
            }
          }
        }
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Audit
        - Key: Purpose
          Value: Validator

  # IAL Healing Orchestrator State Machine
  IALHealingOrchestratorStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: ial-healing-orchestrator
      RoleArn: !GetAtt StepFunctionsRole.Arn
      StateMachineType: STANDARD
      DefinitionString: |
        {
          "Comment": "IAL Healing Orchestrator - Drift Detection & Auto-Heal",
          "StartAt": "DetectDrift",
          "States": {
            "DetectDrift": {
              "Type": "Pass",
              "Parameters": {
                "drift_detected": true,
                "drift_type": "safe",
                "timestamp.$": "$$.State.EnteredTime"
              },
              "Next": "ClassifyDrift"
            },
            "ClassifyDrift": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.drift_type",
                  "StringEquals": "safe",
                  "Next": "AutoHeal"
                },
                {
                  "Variable": "$.drift_type",
                  "StringEquals": "risky",
                  "Next": "CreatePR"
                }
              ],
              "Default": "HealingComplete"
            },
            "AutoHeal": {
              "Type": "Pass",
              "Parameters": {
                "healing_result": "success",
                "action": "auto_healed"
              },
              "Next": "HealingComplete"
            },
            "CreatePR": {
              "Type": "Pass",
              "Parameters": {
                "pr_created": true,
                "pr_url": "https://github.com/owner/repo/pull/123"
              },
              "Next": "HealingComplete"
            },
            "HealingComplete": {
              "Type": "Succeed",
              "OutputPath": "$"
            }
          }
        }
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Healing
        - Key: Purpose
          Value: DriftOrchestrator

Outputs:
  OrchestratorStateMachineArn:
    Description: ARN of the orchestrator state machine
    Value: !Ref OrchestratorStateMachine
    Export:
      Name: !Sub '${ProjectName}-OrchestratorStateMachineArn'
  
  CircuitBreakerStateMachineArn:
    Description: ARN of the circuit breaker state machine
    Value: !Ref CircuitBreakerStateMachine
    Export:
      Name: !Sub '${ProjectName}-CircuitBreakerStateMachineArn'

  IALPhaseManagerArn:
    Description: ARN of the IAL Phase Manager state machine
    Value: !Ref IALPhaseManagerStateMachine
    Export:
      Name: !Sub '${ProjectName}-IALPhaseManagerArn'

  IALAuditValidatorArn:
    Description: ARN of the IAL Audit Validator state machine
    Value: !Ref IALAuditValidatorStateMachine
    Export:
      Name: !Sub '${ProjectName}-IALAuditValidatorArn'

  IALHealingOrchestratorArn:
    Description: ARN of the IAL Healing Orchestrator state machine
    Value: !Ref IALHealingOrchestratorStateMachine
    Export:
      Name: !Sub '${ProjectName}-IALHealingOrchestratorArn'
