phase_name: "IAL FinOps Budget Enforcement"
description: "FinOps budget enforcement with cost estimation, PR commenting, and deployment blocking"
resource_count: 6

Resources:
  # FinOps Budget Enforcement Lambda
  FinOpsBudgetEnforcementLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-finops-budget-enforcement'
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt FinOpsLambdaRole.Arn
      Timeout: 30
      Environment:
        Variables:
          PYTHONPATH: '/opt/python'
          FINOPS_QUIET_MODE: '1'
      Code:
        ZipFile: |
          import json
          import os
          import sys
          import subprocess
          from typing import Dict, Any

          def lambda_handler(event: Dict[str, Any], context) -> Dict[str, Any]:
              try:
                  phases = event.get("phases", [])
                  deployment_type = event.get("deployment_type", "full")
                  budget_override = event.get("budget_override")
                  
                  if not phases:
                      return {
                          "statusCode": 400,
                          "status": "ERROR",
                          "message": "No phases provided for budget enforcement",
                          "can_proceed": False
                      }
                  
                  # Call FinOps MCP for budget enforcement
                  result = call_finops_enforcement(phases, deployment_type, budget_override)
                  
                  return {
                      "statusCode": 200 if result["can_proceed"] else 403,
                      "status": result["enforcement_status"],
                      "message": f"Budget enforcement: {result['enforcement_status']}",
                      "can_proceed": result["can_proceed"],
                      "total_estimated_cost": result["total_estimated_cost"],
                      "total_budget_limit": result["total_budget_limit"],
                      "blocked_phases": result["blocked_phases"],
                      "deployment_type": result["deployment_type"],
                      "finops_result": result
                  }
                  
              except Exception as e:
                  return {
                      "statusCode": 500,
                      "status": "ERROR", 
                      "message": f"Budget enforcement failed: {str(e)}",
                      "can_proceed": False,
                      "error": str(e)
                  }

          def call_finops_enforcement(phases: list, deployment_type: str, budget_override: float = None) -> Dict[str, Any]:
              # Simplified enforcement logic for Lambda
              total_cost = len(phases) * 25.0  # Heuristic: $25 per phase
              budget_limit = 500.0 if deployment_type == "workloads" else 200.0
              
              if budget_override:
                  budget_limit = budget_override
              
              can_proceed = total_cost <= budget_limit
              
              return {
                  "deployment_type": deployment_type,
                  "total_phases": len(phases),
                  "total_estimated_cost": total_cost,
                  "total_budget_limit": budget_limit,
                  "enforcement_status": "PASS" if can_proceed else "BLOCK",
                  "blocked_phases": [] if can_proceed else phases,
                  "can_proceed": can_proceed,
                  "timestamp": "2025-11-03T19:44:00Z"
              }

  # FinOps Lambda IAM Role
  FinOpsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-finops-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: FinOpsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ce:GetCostAndUsage
                  - ce:GetUsageReport
                  - budgets:ViewBudget
                  - sns:Publish
                Resource: '*'

  # FinOps Step Functions State Machine
  FinOpsStepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${ProjectName}-finops-pipeline'
      RoleArn: !GetAtt FinOpsStepFunctionRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "IAL FinOps Budget Enforcement Pipeline",
          "StartAt": "BudgetCheck",
          "States": {
            "BudgetCheck": {
              "Type": "Task",
              "Resource": "${FinOpsBudgetEnforcementLambda.Arn}",
              "Next": "BudgetChoice"
            },
            "BudgetChoice": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.can_proceed",
                  "BooleanEquals": false,
                  "Next": "BudgetExceeded"
                }
              ],
              "Default": "BudgetApproved"
            },
            "BudgetExceeded": {
              "Type": "Fail",
              "Cause": "Budget limit exceeded",
              "Error": "BudgetLimitExceeded"
            },
            "BudgetApproved": {
              "Type": "Succeed"
            }
          }
        }

  # FinOps Step Functions IAM Role
  FinOpsStepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-finops-stepfunction-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FinOpsStepFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt FinOpsBudgetEnforcementLambda.Arn

  # FinOps Alerts SNS Topic
  FinOpsAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-finops-alerts'
      DisplayName: 'IAL FinOps Budget Alerts'

  # FinOps S3 Bucket for Reports
  FinOpsReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-finops-reports-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

# Outputs
Outputs:
  FinOpsBudgetEnforcementLambdaArn:
    Description: 'ARN of the FinOps Budget Enforcement Lambda'
    Value: !GetAtt FinOpsBudgetEnforcementLambda.Arn
    Export:
      Name: !Sub '${ProjectName}-finops-lambda-arn'

  FinOpsStepFunctionArn:
    Description: 'ARN of the FinOps Step Function'
    Value: !Ref FinOpsStepFunction
    Export:
      Name: !Sub '${ProjectName}-finops-stepfunction-arn'

  FinOpsAlertsTopicArn:
    Description: 'ARN of the FinOps Alerts SNS Topic'
    Value: !Ref FinOpsAlertsTopic
    Export:
      Name: !Sub '${ProjectName}-finops-alerts-topic-arn'

  FinOpsReportsBucketName:
    Description: 'Name of the FinOps Reports S3 Bucket'
    Value: !Ref FinOpsReportsBucket
    Export:
      Name: !Sub '${ProjectName}-finops-reports-bucket'

# Metadata
metadata:
  estimated_monthly_cost: '$15.00'
  cost_breakdown:
    lambda_invocations: '$2.00'
    step_functions_executions: '$1.00'
    s3_storage: '$5.00'
    sns_notifications: '$1.00'
    cost_explorer_api: '$6.00'
  finops:
    enforcement_enabled: true
    budget_validation: true
    pr_commenting: true
    deployment_blocking: true

# Parameters
parameters:
  ProjectName:
    Type: String
    Default: ial
    Description: Project name for resource naming
