AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAL Foundation - Feature Flags DynamoDB Table'

Parameters:
  ProjectName:
    Type: String
    Default: ial
    Description: Project name for resource naming

Resources:
  # DynamoDB Table for Feature Flags
  FeatureFlagsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ial-feature-flags
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: flag_name
          AttributeType: S
        - AttributeName: environment
          AttributeType: S
      KeySchema:
        - AttributeName: flag_name
          KeyType: HASH
        - AttributeName: environment
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expire_at
        Enabled: true
      Tags:
        - Key: ial:managed
          Value: 'true'
        - Key: Component
          Value: FeatureFlags

Outputs:
  FeatureFlagsTableName:
    Description: Feature Flags DynamoDB Table Name
    Value: !Ref FeatureFlagsTable
    Export:
      Name: ial-feature-flags-table-name
  
  FeatureFlagsTableArn:
    Description: Feature Flags DynamoDB Table ARN
    Value: !GetAtt FeatureFlagsTable.Arn
    Export:
      Name: ial-feature-flags-table-arn
