# PHASE 23: IAL CORE OBSERVABILITY
# Monitoramento essencial do próprio funcionamento do IAL
# Dependências: 02-logging-infrastructure
# Custo: $8/mês

phase: "23-ial-core-observability"
description: "Core observability for IAL operations monitoring"
depends_on: ["02-logging-infrastructure"]
estimated_cost_monthly: 8.00
resource_count: 8

resources:
  # CloudWatch Dashboard for IAL Core Operations
  IaLCoreOperationsDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: IaL-Core-Operations
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "IaL/Operations", "DeploymentSuccess", "Project", "ial" ],
                  [ ".", "DeploymentFailure", ".", "." ],
                  [ ".", "ValidationSuccess", ".", "." ],
                  [ ".", "ValidationFailure", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "us-east-1",
                "stat": "Sum",
                "period": 300,
                "title": "IAL Core Operations Metrics"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "IaL/Performance", "DeploymentDuration", "Project", "ial" ],
                  [ ".", "ValidationDuration", ".", "." ],
                  [ ".", "RollbackDuration", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "us-east-1",
                "stat": "Average",
                "period": 300,
                "title": "IAL Performance Metrics"
              }
            },
            {
              "type": "log",
              "x": 0,
              "y": 12,
              "width": 24,
              "height": 6,
              "properties": {
                "query": "SOURCE 'ial-infrastructure'\n| fields @timestamp, level, message, phase, event_type\n| filter level = \"ERROR\"\n| sort @timestamp desc\n| limit 20",
                "region": "us-east-1",
                "title": "IAL Core Errors"
              }
            }
          ]
        }
      Tags:
        - Key: Project
          Value: ial
        - Key: Purpose
          Value: core-observability
        - Key: Component
          Value: dashboard

  # Core IAL Alarms
  IaLCoreDeploymentFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: IaL-Core-Deployment-Failures
      AlarmDescription: Alert when IAL core deployment failures occur
      MetricName: DeploymentFailure
      Namespace: IaL/Operations
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref IaLCoreAlertsSnsTopic
      TreatMissingData: notBreaching

  IaLCoreValidationFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: IaL-Core-Validation-Failures
      AlarmDescription: Alert when IAL core validation failures occur
      MetricName: ValidationFailure
      Namespace: IaL/Operations
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref IaLCoreAlertsSnsTopic
      TreatMissingData: notBreaching

  IaLCoreHighDeploymentDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: IaL-Core-High-Deployment-Duration
      AlarmDescription: Alert when IAL core deployments take too long
      MetricName: DeploymentDuration
      Namespace: IaL/Performance
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1800
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref IaLCoreAlertsSnsTopic
      TreatMissingData: notBreaching

  IaLCoreLowCompletionRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: IaL-Core-Low-Completion-Rate
      AlarmDescription: Alert when IAL core completion rate drops below 95%
      MetricName: CompletionRate
      Namespace: IaL/Operations
      Statistic: Average
      Period: 900
      EvaluationPeriods: 2
      Threshold: 95
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref IaLCoreAlertsSnsTopic
      TreatMissingData: notBreaching

  IaLCoreRollbackTriggeredAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: IaL-Core-Rollback-Triggered
      AlarmDescription: Alert when IAL core automatic rollback is triggered
      MetricName: RollbackTriggered
      Namespace: IaL/Operations
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref IaLCoreAlertsSnsTopic
      TreatMissingData: notBreaching

  # SNS Topic for IAL Core Alerts
  IaLCoreAlertsSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ial-core-alerts
      DisplayName: IAL Core System Alerts
      Tags:
        - Key: Project
          Value: ial
        - Key: Purpose
          Value: core-alerting
        - Key: Component
          Value: sns

  # X-Ray Tracing for IAL Core
  IaLCoreTracingRule:
    Type: AWS::XRay::SamplingRule
    Properties:
      SamplingRule:
        RuleName: IaL-Core-Tracing-Rule
        Priority: 9000
        FixedRate: 0.1
        ReservoirSize: 1
        ServiceName: "ial-*"
        ServiceType: "*"
        Host: "*"
        HTTPMethod: "*"
        URLPath: "*"
        Version: 1

  # Container Insights Log Group for IAL Core
  IaLCoreContainerInsightsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/containerinsights/ial-core/performance
      RetentionInDays: 7
      KmsKeyId: !Ref IaLKMSKey
      Tags:
        - Key: Project
          Value: ial
        - Key: Purpose
          Value: core-container-insights
        - Key: Component
          Value: logs

outputs:
  CoreDashboardURL:
    Description: URL to the IAL core operations dashboard
    Value: !Sub "https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=IaL-Core-Operations"
    Export:
      Name: !Sub "${AWS::StackName}-CoreDashboardURL"

  CoreAlertsTopicArn:
    Description: ARN of the IAL core alerts SNS topic
    Value: !Ref IaLCoreAlertsSnsTopic
    Export:
      Name: !Sub "${AWS::StackName}-CoreAlertsTopicArn"

  CoreTracingRuleArn:
    Description: ARN of the IAL core X-Ray tracing rule
    Value: !GetAtt IaLCoreTracingRule.RuleArn
    Export:
      Name: !Sub "${AWS::StackName}-CoreTracingRuleArn"
