AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAL Foundation - Logging Infrastructure'

Parameters:
  ProjectName:
    Type: String
    Default: ial-fork
    Description: Project name for resource naming

Resources:
  # CloudWatch Log Group for IAL operations
  IALLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '${AWS::StackName}-infrastructure'
      RetentionInDays: 30
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: Logging

  # Lambda functions log group
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}'
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: LambdaLogs

  # Step Functions log group
  StepFunctionsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/stepfunctions/${AWS::StackName}'
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: StepFunctionsLogs

Outputs:
  IALLogGroupName:
    Description: Name of the IAL log group
    Value: !Ref IALLogGroup
    Export:
      Name: !Sub '${ProjectName}-36-IALLogGroupName'
  
  IALLogGroupArn:
    Description: ARN of the IAL log group
    Value: !GetAtt IALLogGroup.Arn
    Export:
      Name: !Sub '${ProjectName}-36-IALLogGroupArn'
