AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAL RAG Storage - Additional storage for vector indices (non-duplicate)'

Parameters:
  ProjectName:
    Type: String
    Default: ial-fork
    Description: Project name for resource naming

Resources:
  # S3 Bucket for vector indices (unique name to avoid conflicts)
  VectorIndicesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-vector-indices-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: VectorIndices

Outputs:
  VectorIndicesBucketName:
    Description: Name of the vector indices bucket
    Value: !Ref VectorIndicesBucket
    Export:
      Name: !Sub '${ProjectName}-41-VectorIndicesBucketName'
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Foundation
        - Key: Purpose
          Value: VectorIndices

Outputs:
  RAGStorageBucketName:
    Description: Name of the RAG storage bucket
    Value: !Ref RAGStorageBucket
    Export:
      Name: !Sub '${ProjectName}-41-RAGStorageBucketName'
  
  VectorIndicesBucketName:
    Description: Name of the vector indices bucket
    Value: !Ref VectorIndicesBucket
    Export:
      Name: !Sub '${ProjectName}-41-VectorIndicesBucketName'
