AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS WAF v2 for API Gateway Protection - Simplified'

Parameters:
  Environment:
    Type: String
    Default: prod
    Description: Environment name

Resources:
  # WAF v2 Web ACL
  IALWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub 'ial-waf-${Environment}-${AWS::StackName}'
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "ial-waf-${Environment}"
      Rules:
        # Rate Limiting Rule
        - Name: RateLimitRule
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 1000
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule

        # AWS Managed Rules - Common Rule Set
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CommonRuleSet

        # AWS Managed Rules - SQL Injection
        - Name: AWSManagedRulesSQLiRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: SQLiRuleSet

  # CloudWatch Log Group for WAF
  WAFLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/wafv2/ial-waf-${Environment}-${AWS::StackName}"
      RetentionInDays: 30

Outputs:
  WebACLArn:
    Description: 'WAF Web ACL ARN'
    Value: !GetAtt IALWebACL.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WebACL-Arn'
  
  WebACLId:
    Description: 'WAF Web ACL ID'
    Value: !Ref IALWebACL
    Export:
      Name: !Sub '${AWS::StackName}-WebACL-Id'
