AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS WAF v2 for API Gateway Protection'

Parameters:
  Environment:
    Type: String
    Default: prod
    Description: Environment name

Resources:
  # WAF v2 Web ACL
  IALWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub 'ial-api-gateway-waf-${Environment}'
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      Rules:
        # Rate Limiting Rule
        - Name: RateLimitRule
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 1000
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule
        
        # OWASP Core Rule Set
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CommonRuleSetMetric
        
        # SQL Injection Protection
        - Name: AWSManagedRulesSQLiRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: SQLiRuleSetMetric

  # CloudWatch Log Group for WAF
  WAFLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/wafv2/ial-api-gateway-waf-${Environment}'
      RetentionInDays: 30

  # WAF Logging Configuration
  WAFLoggingConfiguration:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      ResourceArn: !GetAtt IALWebACL.Arn
      LogDestinationConfigs:
        - !GetAtt WAFLogGroup.Arn

Outputs:
  WebACLArn:
    Description: ARN of the WAF Web ACL
    Value: !GetAtt IALWebACL.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WebACL-Arn'
  
  WebACLId:
    Description: ID of the WAF Web ACL
    Value: !Ref IALWebACL
    Export:
      Name: !Sub '${AWS::StackName}-WebACL-Id'
