AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAL Circuit Breaker Metrics Publisher - Simplified Version'

Parameters:
  ProjectName:
    Type: String
    Default: ial
    Description: Project name for resource naming
  Environment:
    Type: String
    Default: prod
    Description: Environment name

Resources:

  # IAM Role for Lambda
  CircuitBreakerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-circuit-breaker-role-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      Path: /

  # Lambda Function for Circuit Breaker Metrics
  CircuitBreakerMetricsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-circuit-breaker-metrics-${Environment}-${AWS::StackName}'
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt CircuitBreakerLambdaRole.Arn
      Timeout: 60
      MemorySize: 256
      Code:
        ZipFile: |
          import json
          import boto3
          import logging
          
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          def lambda_handler(event, context):
              logger.info("Circuit Breaker Metrics Publisher started")
              
              # Publish sample metrics
              cloudwatch = boto3.client('cloudwatch')
              
              try:
                  cloudwatch.put_metric_data(
                      Namespace='IAL/CircuitBreaker',
                      MetricData=[
                          {
                              'MetricName': 'CircuitBreakerStatus',
                              'Value': 1,
                              'Unit': 'Count'
                          }
                      ]
                  )
                  
                  logger.info("Metrics published successfully")
                  return {
                      'statusCode': 200,
                      'body': json.dumps('Circuit breaker metrics published')
                  }
              except Exception as e:
                  logger.error(f"Error publishing metrics: {str(e)}")
                  return {
                      'statusCode': 500,
                      'body': json.dumps(f'Error: {str(e)}')
                  }

  # CloudWatch Alarm for Circuit Breaker
  CircuitBreakerAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-circuit-breaker-alarm-${Environment}-${AWS::StackName}'
      AlarmDescription: 'Circuit Breaker Status Alarm'
      MetricName: CircuitBreakerStatus
      Namespace: IAL/CircuitBreaker
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: LessThanThreshold
      TreatMissingData: breaching

  # CloudWatch Dashboard
  CircuitBreakerDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${ProjectName}-circuit-breaker-dashboard-${Environment}-${AWS::StackName}'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "IAL/CircuitBreaker", "CircuitBreakerStatus" ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Circuit Breaker Status"
              }
            }
          ]
        }

Outputs:
  LambdaFunctionName:
    Description: "Circuit Breaker Lambda Function Name"
    Value: !Ref CircuitBreakerMetricsFunction
    Export:
      Name: !Sub "${AWS::StackName}-lambda-function-name"

  DashboardURL:
    Description: "Circuit Breaker CloudWatch Dashboard URL"
    Value: !Sub "https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${ProjectName}-circuit-breaker-dashboard-${Environment}-${AWS::StackName}"
    Export:
      Name: !Sub "${AWS::StackName}-dashboard-url"
