AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAL Bedrock Agent Foundation - Cognitive Brain'

Parameters:
  ProjectName:
    Type: String
    Default: ial
  Environment:
    Type: String
    Default: prod

Resources:
  # IAM Role for Bedrock Agent
  IALBedrockAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'AmazonBedrockExecutionRoleForAgents_${ProjectName}_${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: IALAgentExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Lambda invocation permissions
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ProjectName}-*'
              # Step Functions permissions
              - Effect: Allow
                Action:
                  - states:StartExecution
                  - states:DescribeExecution
                  - states:StopExecution
                Resource:
                  - !Sub 'arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${ProjectName}-*'
              # DynamoDB permissions
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ProjectName}-*'
              # S3 permissions
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${ProjectName}-*'
                  - !Sub 'arn:aws:s3:::${ProjectName}-*/*'
              # CloudFormation permissions
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackResources
                  - cloudformation:ListStacks
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: IAL-Cognitive-Foundation

Outputs:
  IALAgentRoleArn:
    Description: 'IAL Bedrock Agent Role ARN'
    Value: !GetAtt IALBedrockAgentRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-agent-role-arn'
  
  BedrockAgentsSupported:
    Description: 'Whether Bedrock Agents are supported in this region'
    Value: 'role-created'
    Export:
      Name: !Sub '${AWS::StackName}-bedrock-agents-supported'
