AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAL Foundation - Domain Metadata'

Parameters:
  ProjectName:
    Type: String
    Default: ial
  Environment:
    Type: String
    Default: prod

Resources:
  DomainMetadataParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ProjectName}/${Environment}/domain/metadata"
      Type: String
      Value: |
        {
          "domain": "foundation",
          "description": "Core infrastructure foundation",
          "team_owner": "platform-team",
          "risk_level": "low"
        }
      Description: "Domain metadata for IAL Foundation"

Outputs:
  DomainMetadataArn:
    Description: "Domain metadata parameter ARN"
    Value: !Ref DomainMetadataParameter
    Export:
      Name: !Sub "${AWS::StackName}-domain-metadata-arn"
