#!/usr/bin/env python3
"""
Template Generator for IAL
Generates CloudFormation templates based on user intent
"""

import os
import yaml
from typing import Dict, List

class TemplateGenerator:
    def __init__(self, config: Dict):
        self.config = config
        self.base_templates_dir = "/home/ial/phases"
    
    def generate_from_intent(self, intent: Dict) -> Dict:
        """Generate CloudFormation templates based on user intent"""
        
        templates = {}
        
        for domain in intent['domains']:
            if domain == 'foundation':
                templates.update(self.generate_foundation_templates())
            elif domain == 'security':
                templates.update(self.generate_security_templates())
            elif domain == 'networking':
                templates.update(self.generate_networking_templates())
            # Add other domains as needed
        
        # Replace variables with user-specific values
        return self.replace_template_variables(templates)
    
    def generate_foundation_templates(self) -> Dict:
        """Generate foundation infrastructure templates"""
        templates = {}
        
        # DynamoDB State Table
        templates['phases/00-foundation/01-dynamodb-state.yaml'] = self.load_and_customize_template(
            '00-foundation/01-dynamodb-state.yaml'
        )
        
        # KMS Keys
        templates['phases/00-foundation/02-kms-keys.yaml'] = self.load_and_customize_template(
            '00-foundation/02-kms-keys.yaml'
        )
        
        # IAM Roles
        templates['phases/00-foundation/04-iam-roles.yaml'] = self.load_and_customize_template(
            '00-foundation/04-iam-roles.yaml'
        )
        
        # Memory Resources - DynamoDB Tables
        templates['phases/00-foundation/07-conversation-memory.yaml'] = self.load_and_customize_template(
            '00-foundation/07-conversation-memory.yaml'
        )
        
        # Memory Resources - S3 Bucket  
        templates['phases/00-foundation/06-memory-s3.yaml'] = self.load_and_customize_template(
            '00-foundation/06-memory-s3.yaml'
        )
        
        # Memory Resources - IAM Roles
        templates['phases/00-foundation/07-memory-iam.yaml'] = self.load_and_customize_template(
            '00-foundation/07-memory-iam.yaml'
        )
        
        return templates
    
    def generate_security_templates(self) -> Dict:
        """Generate security infrastructure templates"""
        templates = {}
        
        # Security services
        templates['phases/10-security/01-kms-security.yaml'] = self.load_and_customize_template(
            '10-security/01-kms-security.yaml'
        )
        
        return templates
    
    def generate_networking_templates(self) -> Dict:
        """Generate networking infrastructure templates"""
        templates = {}
        
        # VPC and networking
        templates['phases/20-network/01-networking.yaml'] = self.load_and_customize_template(
            '20-network/01-networking.yaml'
        )
        
        return templates
    
    def load_and_customize_template(self, template_path: str) -> str:
        """Load template from phases directory and customize"""
        full_path = os.path.join(self.base_templates_dir, template_path)
        
        try:
            with open(full_path, 'r') as f:
                content = f.read()
            return content
        except FileNotFoundError:
            # Return a basic template if file doesn't exist
            return self.create_basic_template(template_path)
    
    def create_basic_template(self, template_path: str) -> str:
        """Create a basic CloudFormation template"""
        template_name = os.path.basename(template_path).replace('.yaml', '')
        
        basic_template = {
            'AWSTemplateFormatVersion': '2010-09-09',
            'Description': f'IAL Generated Template - {template_name}',
            'Parameters': {
                'ProjectName': {
                    'Type': 'String',
                    'Default': '{{PROJECT_NAME}}',
                    'Description': 'Project name for resource naming'
                }
            },
            'Resources': {
                'PlaceholderResource': {
                    'Type': 'AWS::CloudFormation::WaitConditionHandle',
                    'Properties': {}
                }
            },
            'Outputs': {
                'TemplateGenerated': {
                    'Description': 'Template generated by IAL',
                    'Value': f'{template_name} - Generated automatically'
                }
            }
        }
        
        return yaml.dump(basic_template, default_flow_style=False)
    
    def replace_template_variables(self, templates: Dict) -> Dict:
        """Replace template variables with user config"""
        replacements = {
            '{{AWS_ACCOUNT_ID}}': self.config.get('AWS_ACCOUNT_ID', ''),
            '{{PROJECT_NAME}}': self.config.get('PROJECT_NAME', ''),
            '{{AWS_REGION}}': self.config.get('AWS_REGION', 'us-east-1'),
            '{{EXECUTOR_NAME}}': self.config.get('EXECUTOR_NAME', ''),
            '{{GITHUB_USER}}': self.config.get('GITHUB_USER', ''),
            '{{GITHUB_REPOSITORY}}': self.config.get('GITHUB_REPOSITORY', '')
        }
        
        processed_templates = {}
        for path, content in templates.items():
            for old, new in replacements.items():
                content = content.replace(old, new)
            processed_templates[path] = content
        
        return processed_templates
